FEAT: loadOrCreateFactory
gammaswap/v0-subgraph pull request #12
Opened 2023-01-26 23:07 UTC by fhd1423

Created loadOrCreateFactory to check if a factory exists or creates one at the beginning of handlePoolCreated

2023-01-31 23:03 UTC, Pochetes requested changes
The `GSFactory` and `Pool` entities need to be updated. Check for whitespaces and make sure correct names are used

2023-01-31 23:03 UTC, Pochetes commented on schema.graphql
> +	txCount: BigInt! # transactions for all pools
it looks like you have 4 spaces instead of 2 for your tabs in vscode. change them in your settings or if you want to keep them, change them directly here.

2023-01-31 23:03 UTC, Pochetes commented on src/mappings/GammaPoolFactory.ts
>      overview = new GSFactory('1')
use GS Factory address instead

2023-01-31 23:03 UTC, Pochetes commented on src/mappings/GammaPoolFactory.ts
>      overview = new GSFactory('1')
also call this the factory not overview

2023-01-31 23:03 UTC, Pochetes commented on src/mappings/GammaPoolFactory.ts
>    overview.save()
you don't need a createdPools property, just increment poolCount by 1, outside of this function.

2023-01-31 23:03 UTC, Pochetes commented on src/mappings/GammaPoolFactory.ts
>    overview.save()
return the factory to make this possible

2023-01-31 23:08 UTC, fhd1423 commented on src/mappings/GammaPoolFactory.ts
>    overview.save()
i was using the createdPools in order to store addresses so that i could query the pools to get the overall metrics

2023-01-31 23:15 UTC, Pochetes commented on src/mappings/GammaPoolFactory.ts
>    overview.save()
calculating usage metrics is a task for later, let's make sure we're gradually improving the repo and not do everything all at once.

we're going to load all the pool entities inside the `handlePoolUpdated` function, do calcs, and then store metrics inside GSFactory. No need to store pools there

2023-02-01 04:03 UTC, Pochetes commented
FYI: updated the ABIs of the smart contracts, so you should have the new events. make sure you take those updates into account for your PR

2023-02-02 16:25 UTC, Pochetes requested changes
left a set of improvements to make, next PR will be implementation of the `getOrLoadERC20Tokens`

2023-02-02 16:25 UTC, Pochetes commented on schema.graphql
> +	tokens: [Token!]!
make sure to take a look at the `Pool` entity again.

missing `lpTokenBalance`, `lpTokenBorrowed`, `lpTokenBorrowedPlusInterest`, `lpInvariant`, `borrowedInvariant`

remove `suppliedLiquidity`, `borrowedLiquidity` and `totalCollateral` for now. we have the invariants to start with.

2023-02-02 16:25 UTC, Pochetes commented on src/mappings/GammaPoolFactory.ts
> +  poolCreated.tokenBalances = [ZERO_BI, ZERO_BI]
update according to new changes to `Pool` entity props

2023-02-02 16:25 UTC, Pochetes commented on schema.graphql
>  type GSFactory @entity {
update the `GSFactory` entity props. refer to the notion doc

2023-02-02 16:25 UTC, Pochetes commented on src/mappings/GammaPoolFactory.ts
> +  factory.save()
increment `poolCount` by 1

2023-02-02 16:25 UTC, Pochetes commented on src/mappings/helpers.ts
> +export const FactoryAddress = '0x862654Cfa91cEfb48A3D55108c353eC2Bca1794A'
constants should be all caps

2023-02-02 20:50 UTC, Pochetes approved these changes
Made some changes myself. Can sign this off and move on to next PR

2023-02-02 20:51 UTC, merged