working subgraph base
gammaswap/v0-subgraph pull request #2
Opened 2022-08-31 23:02 UTC by Pochetes

# Subgraph
- Polished the layout for a working subgraph
- Only configured for the PositionManager contract

2022-08-31 23:18 UTC, dam417 requested changes
Rename CreateLoanEntity to just Loan and probably shouldn't be pushing the build and generated directories.

2022-08-31 23:37 UTC, TBomberman commented on abis/PositionManager.json
> +[
Isn't this redundant with build/PositionManager/abis/PositionManager.json?

2022-08-31 23:37 UTC, TBomberman commented on networks.json
> +      "address": "0x19cEcCd6942ad38562Ee10bAfd44776ceB67e923"
How is this obtained? I guess this value will change.

2022-08-31 23:37 UTC, TBomberman commented on subgraph.yaml
> +      address: "0x19cEcCd6942ad38562Ee10bAfd44776ceB67e923"
this value will change

2022-08-31 23:37 UTC, TBomberman commented on tests/position-manager.test.ts
> +      "0xa16081f360e3847006db660bae1c6d1b2e17ec2a",
not sure if these should be hard coded.

2022-08-31 23:41 UTC, dam417 commented on networks.json
> +      "address": "0x19cEcCd6942ad38562Ee10bAfd44776ceB67e923"
oh yeah, we're going to have to keep track of the addresses here. That's why I'm thinking we might need predetermined addresses to not have to be changing this stuff all the time

2022-09-01 00:41 UTC, Pochetes commented on subgraph.yaml
> +      address: "0x19cEcCd6942ad38562Ee10bAfd44776ceB67e923"
Yeah, how will we keep track of these changes?

2022-09-01 01:31 UTC, Pochetes commented on abis/PositionManager.json
> +[
Correct, removing it

2022-09-01 02:12 UTC, Pochetes commented on subgraph.yaml
> +      address: "0x19cEcCd6942ad38562Ee10bAfd44776ceB67e923"
For now, I will have it in environment variables

2022-09-01 02:29 UTC, Pochetes commented on networks.json
> +      "address": "0x19cEcCd6942ad38562Ee10bAfd44776ceB67e923"
yes, I will make a config file storing all this

2022-09-01 04:59 UTC, Pochetes commented on tests/position-manager.test.ts
> +      "0xa16081f360e3847006db660bae1c6d1b2e17ec2a",
If they're tests, shouldn't they be hard coded, since we are placing these tests in a vacuum environment?

2022-09-01 05:00 UTC, Pochetes commented on subgraph.yaml
> +      address: "0x19cEcCd6942ad38562Ee10bAfd44776ceB67e923"
Done.

2022-09-01 06:09 UTC, TBomberman commented on tests/position-manager.test.ts
> +      "0xa16081f360e3847006db660bae1c6d1b2e17ec2a",
got it, ty

2022-09-01 17:58 UTC, TBomberman approved these changes

2022-09-20 09:49 UTC, UsamaSaleem14 commented
Template mapping for dynamic contracts.
I have added template mapping for ShortStrategy. This is still needed to be tested as we are still working on strategies contracts.

2022-10-05 06:23 UTC, dam417 approved these changes
We don't need to handle PositionManager events, unless you think they should be handled for some reason.
ShortStrategy.ts should probably be changed to just GammaPool.ts.
I think the schema looks good. 
I suppose, this is a layout. As a starting point. It's fine.

2022-10-07 18:15 UTC, merged